/**
 * Incident Management Dashboard Template
 * Pre-configured dashboard for incident tracking
 */

import type { DashboardTemplate } from '../types.js';

export const incidentDashboardTemplate: DashboardTemplate = {
  id: 'incident_dashboard',
  name: 'Incident Management Dashboard',
  description: 'Comprehensive incident tracking dashboard with priority, state, and assignment views',
  category: 'IT Service Management',
  config: {
    name: 'incident_dashboard',
    title: 'Incident Management',
    description: 'Real-time incident tracking and management',
    type: 'service',
    layout: {
      columns: 12,
      rows: 3,
      responsive: true,
    },
    widgets: [
      {
        id: 'critical_incidents',
        type: 'table',
        title: 'Critical Incidents',
        position: { row: 0, column: 0 },
        size: { width: 6, height: 400 },
        dataSource: {
          table: 'incident',
          fields: ['number', 'short_description', 'state', 'assigned_to', 'opened_at'],
          filter: 'active=true^priority=1',
          orderBy: 'opened_at',
          limit: 10,
        },
        config: {
          columns: [
            {
              field: 'number',
              label: 'Number',
              sortable: true,
              filterable: true,
              type: 'text',
              renderer: 'link',
            },
            {
              field: 'short_description',
              label: 'Description',
              sortable: true,
              filterable: true,
              type: 'text',
            },
            {
              field: 'state',
              label: 'State',
              sortable: true,
              filterable: true,
              type: 'choice',
              renderer: 'badge',
              colorCoding: {
                field: 'state',
                mapping: [
                  { value: '1', color: '#17a2b8' },
                  { value: '2', color: '#ffc107' },
                  { value: '6', color: '#28a745' },
                ],
              },
            },
            {
              field: 'assigned_to',
              label: 'Assigned To',
              sortable: true,
              filterable: true,
              type: 'reference',
            },
            {
              field: 'opened_at',
              label: 'Opened',
              sortable: true,
              filterable: false,
              type: 'datetime',
              format: 'MM/dd/yyyy HH:mm',
            },
          ],
          style: 'list',
          striped: true,
          bordered: true,
          hover: true,
          compact: false,
          sortable: true,
          filterable: true,
          paginated: true,
          rowsPerPage: 10,
          selectable: false,
        },
        interactions: {
          clickable: true,
          export: true,
          tooltip: true,
        },
      },
      {
        id: 'incident_stats',
        type: 'stat',
        title: 'Active Incidents',
        position: { row: 0, column: 6 },
        size: { width: 2, height: 200 },
        dataSource: {
          table: 'incident',
          fields: ['sys_id'],
          filter: 'active=true',
          aggregation: {
            groupBy: [],
            functions: [{ field: 'sys_id', function: 'COUNT' }],
          },
        },
        config: {
          valueField: 'count',
          label: 'Active',
          format: 'number',
          icon: 'fa-exclamation-circle',
        },
      },
      {
        id: 'resolved_stats',
        type: 'stat',
        title: 'Resolved Today',
        position: { row: 0, column: 8 },
        size: { width: 2, height: 200 },
        dataSource: {
          table: 'incident',
          fields: ['sys_id'],
          filter: 'state=6^resolved_atONToday@javascript:gs.beginningOfToday()@javascript:gs.endOfToday()',
          aggregation: {
            groupBy: [],
            functions: [{ field: 'sys_id', function: 'COUNT' }],
          },
        },
        config: {
          valueField: 'count',
          label: 'Resolved',
          format: 'number',
          icon: 'fa-check-circle',
        },
      },
      {
        id: 'avg_resolution_time',
        type: 'stat',
        title: 'Avg Resolution Time',
        position: { row: 0, column: 10 },
        size: { width: 2, height: 200 },
        dataSource: {
          table: 'incident',
          fields: ['calendar_duration'],
          filter: 'state=6^resolved_atONToday@javascript:gs.beginningOfToday()@javascript:gs.endOfToday()',
          aggregation: {
            groupBy: [],
            functions: [{ field: 'calendar_duration', function: 'AVG' }],
          },
        },
        config: {
          valueField: 'avg_duration',
          label: 'Avg Time',
          format: 'duration',
          icon: 'fa-clock',
        },
      },
      {
        id: 'all_incidents',
        type: 'table',
        title: 'All Active Incidents',
        position: { row: 1, column: 0 },
        size: { width: 12, height: 400 },
        dataSource: {
          table: 'incident',
          fields: [
            'number',
            'short_description',
            'priority',
            'state',
            'assigned_to',
            'category',
            'opened_at',
          ],
          filter: 'active=true',
          orderBy: 'priority',
          limit: 25,
        },
        config: {
          columns: [
            {
              field: 'number',
              label: 'Number',
              sortable: true,
              filterable: true,
              type: 'text',
              renderer: 'link',
            },
            {
              field: 'short_description',
              label: 'Description',
              sortable: true,
              filterable: true,
              type: 'text',
            },
            {
              field: 'priority',
              label: 'Priority',
              sortable: true,
              filterable: true,
              type: 'choice',
              renderer: 'badge',
              align: 'center',
              colorCoding: {
                field: 'priority',
                mapping: [
                  { value: '1', color: '#dc3545' },
                  { value: '2', color: '#fd7e14' },
                  { value: '3', color: '#ffc107' },
                  { value: '4', color: '#28a745' },
                ],
              },
            },
            {
              field: 'state',
              label: 'State',
              sortable: true,
              filterable: true,
              type: 'choice',
              renderer: 'badge',
              align: 'center',
            },
            {
              field: 'assigned_to',
              label: 'Assigned To',
              sortable: true,
              filterable: true,
              type: 'reference',
            },
            {
              field: 'category',
              label: 'Category',
              sortable: true,
              filterable: true,
              type: 'text',
            },
            {
              field: 'opened_at',
              label: 'Opened',
              sortable: true,
              filterable: false,
              type: 'datetime',
              format: 'MM/dd/yyyy HH:mm',
            },
          ],
          style: 'list',
          striped: true,
          bordered: true,
          hover: true,
          compact: false,
          sortable: true,
          filterable: true,
          paginated: true,
          rowsPerPage: 25,
          selectable: true,
        },
        interactions: {
          clickable: true,
          export: true,
          tooltip: true,
        },
      },
    ],
    theme: {
      primaryColor: '#0066cc',
      backgroundColor: '#f5f5f5',
      headerColor: '#333333',
      textColor: '#333333',
      borderColor: '#dddddd',
      cardShadow: true,
    },
    refreshInterval: 60, // Refresh every 60 seconds
  },
};
